use crate::OneDarkStyle;
use crate::GLOBAL_CONFIG;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Debug, Clone)]
#[serde(default)]
pub struct ColorPalette {
    pub black: Box<str>,
    pub bg0: Box<str>,
    pub bg1: Box<str>,
    pub bg2: Box<str>,
    pub bg3: Box<str>,
    pub bg_d: Box<str>,
    pub bg_blue: Box<str>,
    pub bg_yellow: Box<str>,
    pub fg: Box<str>,
    pub purple: Box<str>,
    pub green: Box<str>,
    pub orange: Box<str>,
    pub blue: Box<str>,
    pub yellow: Box<str>,
    pub cyan: Box<str>,
    pub red: Box<str>,
    pub grey: Box<str>,
    pub light_grey: Box<str>,
    pub dark_cyan: Box<str>,
    pub dark_red: Box<str>,
    pub dark_yellow: Box<str>,
    pub dark_purple: Box<str>,
    pub diff_add: Box<str>,
    pub diff_delete: Box<str>,
    pub diff_change: Box<str>,
    pub diff_text: Box<str>,
}

#[derive(Deserialize, Debug, Clone, Default)]
pub struct ConfigColorPalette {
    pub black: Option<Box<str>>,
    pub bg0: Option<Box<str>>,
    pub bg1: Option<Box<str>>,
    pub bg2: Option<Box<str>>,
    pub bg3: Option<Box<str>>,
    pub bg_d: Option<Box<str>>,
    pub bg_blue: Option<Box<str>>,
    pub bg_yellow: Option<Box<str>>,
    pub fg: Option<Box<str>>,
    pub purple: Option<Box<str>>,
    pub green: Option<Box<str>>,
    pub orange: Option<Box<str>>,
    pub blue: Option<Box<str>>,
    pub yellow: Option<Box<str>>,
    pub cyan: Option<Box<str>>,
    pub red: Option<Box<str>>,
    pub grey: Option<Box<str>>,
    pub light_grey: Option<Box<str>>,
    pub dark_cyan: Option<Box<str>>,
    pub dark_red: Option<Box<str>>,
    pub dark_yellow: Option<Box<str>>,
    pub dark_purple: Option<Box<str>>,
    pub diff_add: Option<Box<str>>,
    pub diff_delete: Option<Box<str>>,
    pub diff_change: Option<Box<str>>,
    pub diff_text: Option<Box<str>>,
}

pub fn get_palette(style: OneDarkStyle) -> ColorPalette {
    match style {
        OneDarkStyle::Dark => ColorPalette {
            black: "#181a1f".into(),
            bg0: "#282c34".into(),
            bg1: "#31353f".into(),
            bg2: "#393f4a".into(),
            bg3: "#3b3f4c".into(),
            bg_d: "#21252b".into(),
            bg_blue: "#73b8f1".into(),
            bg_yellow: "#ebd09c".into(),
            fg: "#abb2bf".into(),
            purple: "#c678dd".into(),
            green: "#98c379".into(),
            orange: "#d19a66".into(),
            blue: "#61afef".into(),
            yellow: "#e5c07b".into(),
            cyan: "#56b6c2".into(),
            red: "#e86671".into(),
            grey: "#5c6370".into(),
            light_grey: "#848b98".into(),
            dark_cyan: "#2b6f77".into(),
            dark_red: "#993939".into(),
            dark_yellow: "#93691d".into(),
            dark_purple: "#8a3fa0".into(),
            diff_add: "#31392b".into(),
            diff_delete: "#382b2c".into(),
            diff_change: "#1c3448".into(),
            diff_text: "#2c5372".into(),
        },
        OneDarkStyle::Darker => ColorPalette {
            black: "#0e1013".into(),
            bg0: "#1f2329".into(),
            bg1: "#282c34".into(),
            bg2: "#30363f".into(),
            bg3: "#323641".into(),
            bg_d: "#181b20".into(),
            bg_blue: "#61afef".into(),
            bg_yellow: "#e8c88c".into(),
            fg: "#a0a8b7".into(),
            purple: "#bf68d9".into(),
            green: "#8ebd6b".into(),
            orange: "#cc9057".into(),
            blue: "#4fa6ed".into(),
            yellow: "#e2b86b".into(),
            cyan: "#48b0bd".into(),
            red: "#e55561".into(),
            grey: "#535965".into(),
            light_grey: "#7a818e".into(),
            dark_cyan: "#266269".into(),
            dark_red: "#8b3434".into(),
            dark_yellow: "#835d1a".into(),
            dark_purple: "#7e3992".into(),
            diff_add: "#272e23".into(),
            diff_delete: "#2d2223".into(),
            diff_change: "#172a3a".into(),
            diff_text: "#274964".into(),
        },
        OneDarkStyle::Cool => ColorPalette {
            black: "#151820".into(),
            bg0: "#242b38".into(),
            bg1: "#2d3343".into(),
            bg2: "#343e4f".into(),
            bg3: "#363c51".into(),
            bg_d: "#1e242e".into(),
            bg_blue: "#6db9f7".into(),
            bg_yellow: "#f0d197".into(),
            fg: "#a5b0c5".into(),
            purple: "#ca72e4".into(),
            green: "#97ca72".into(),
            orange: "#d99a5e".into(),
            blue: "#5ab0f6".into(),
            yellow: "#ebc275".into(),
            cyan: "#4dbdcb".into(),
            red: "#ef5f6b".into(),
            grey: "#546178".into(),
            light_grey: "#7d899f".into(),
            dark_cyan: "#25747d".into(),
            dark_red: "#a13131".into(),
            dark_yellow: "#9a6b16".into(),
            dark_purple: "#8f36a9".into(),
            diff_add: "#303d27".into(),
            diff_delete: "#3c2729".into(),
            diff_change: "#18344c".into(),
            diff_text: "#265478".into(),
        },
        OneDarkStyle::Deep => ColorPalette {
            black: "#0c0e15".into(),
            bg0: "#1a212e".into(),
            bg1: "#21283b".into(),
            bg2: "#283347".into(),
            bg3: "#2a324a".into(),
            bg_d: "#141b24".into(),
            bg_blue: "#54b0fd".into(),
            bg_yellow: "#f2cc81".into(),
            fg: "#93a4c3".into(),
            purple: "#c75ae8".into(),
            green: "#8bcd5b".into(),
            orange: "#dd9046".into(),
            blue: "#41a7fc".into(),
            yellow: "#efbd5d".into(),
            cyan: "#34bfd0".into(),
            red: "#f65866".into(),
            grey: "#455574".into(),
            light_grey: "#6c7d9c".into(),
            dark_cyan: "#1b6a73".into(),
            dark_red: "#992525".into(),
            dark_yellow: "#8f610d".into(),
            dark_purple: "#862aa1".into(),
            diff_add: "#27341c".into(),
            diff_delete: "#331c1e".into(),
            diff_change: "#102b40".into(),
            diff_text: "#1c4a6e".into(),
        },
        OneDarkStyle::Warm => ColorPalette {
            black: "#191a1c".into(),
            bg0: "#2c2d30".into(),
            bg1: "#35373b".into(),
            bg2: "#3e4045".into(),
            bg3: "#404247".into(),
            bg_d: "#242628".into(),
            bg_blue: "#79b7eb".into(),
            bg_yellow: "#e6cfa1".into(),
            fg: "#b1b4b9".into(),
            purple: "#c27fd7".into(),
            green: "#99bc80".into(),
            orange: "#c99a6e".into(),
            blue: "#68aee8".into(),
            yellow: "#dfbe81".into(),
            cyan: "#5fafb9".into(),
            red: "#e16d77".into(),
            grey: "#646568".into(),
            light_grey: "#8b8d91".into(),
            dark_cyan: "#316a71".into(),
            dark_red: "#914141".into(),
            dark_yellow: "#8c6724".into(),
            dark_purple: "#854897".into(),
            diff_add: "#32352f".into(),
            diff_delete: "#342f2f".into(),
            diff_change: "#203444".into(),
            diff_text: "#32526c".into(),
        },
        OneDarkStyle::Warmer => ColorPalette {
            black: "#101012".into(),
            bg0: "#232326".into(),
            bg1: "#2c2d31".into(),
            bg2: "#35363b".into(),
            bg3: "#37383d".into(),
            bg_d: "#1b1c1e".into(),
            bg_blue: "#68aee8".into(),
            bg_yellow: "#e2c792".into(),
            fg: "#a7aab0".into(),
            purple: "#bb70d2".into(),
            green: "#8fb573".into(),
            orange: "#c49060".into(),
            blue: "#57a5e5".into(),
            yellow: "#dbb671".into(),
            cyan: "#51a8b3".into(),
            red: "#de5d68".into(),
            grey: "#5a5b5e".into(),
            light_grey: "#818387".into(),
            dark_cyan: "#2b5d63".into(),
            dark_red: "#833b3b".into(),
            dark_yellow: "#7c5c20".into(),
            dark_purple: "#79428a".into(),
            diff_add: "#282b26".into(),
            diff_delete: "#2a2626".into(),
            diff_change: "#1a2a37".into(),
            diff_text: "#2c485f".into(),
        },
        OneDarkStyle::Light => ColorPalette {
            black: "#101012".into(),
            bg0: "#fafafa".into(),
            bg1: "#f0f0f0".into(),
            bg2: "#e6e6e6".into(),
            bg3: "#dcdcdc".into(),
            bg_d: "#c9c9c9".into(),
            bg_blue: "#68aee8".into(),
            bg_yellow: "#e2c792".into(),
            fg: "#383a42".into(),
            purple: "#a626a4".into(),
            green: "#50a14f".into(),
            orange: "#c18401".into(),
            blue: "#4078f2".into(),
            yellow: "#986801".into(),
            cyan: "#0184bc".into(),
            red: "#e45649".into(),
            grey: "#a0a1a7".into(),
            light_grey: "#818387".into(),
            dark_cyan: "#2b5d63".into(),
            dark_red: "#833b3b".into(),
            dark_yellow: "#7c5c20".into(),
            dark_purple: "#79428a".into(),
            diff_add: "#e2fbe4".into(),
            diff_delete: "#fce2e5".into(),
            diff_change: "#e2ecfb".into(),
            diff_text: "#cad3e0".into(),
        },
    }
}

pub fn merge_palletes() -> ColorPalette {
    let def_palette = ColorPalette::default();
    let new_colors = match GLOBAL_CONFIG.read() {
        Ok(config) => config.colors.clone().unwrap_or_default(),
        Err(_) => ConfigColorPalette::default(),
    };

    ColorPalette {
        black: new_colors.black.unwrap_or(def_palette.black),
        bg0: new_colors.bg0.unwrap_or(def_palette.bg0),
        bg1: new_colors.bg1.unwrap_or(def_palette.bg1),
        bg2: new_colors.bg2.unwrap_or(def_palette.bg2),
        bg3: new_colors.bg3.unwrap_or(def_palette.bg3),
        bg_d: new_colors.bg_d.unwrap_or(def_palette.bg_d),
        bg_blue: new_colors.bg_blue.unwrap_or(def_palette.bg_blue),
        bg_yellow: new_colors.bg_yellow.unwrap_or(def_palette.bg_yellow),
        fg: new_colors.fg.unwrap_or(def_palette.fg),
        purple: new_colors.purple.unwrap_or(def_palette.purple),
        green: new_colors.green.unwrap_or(def_palette.green),
        orange: new_colors.orange.unwrap_or(def_palette.orange),
        blue: new_colors.blue.unwrap_or(def_palette.blue),
        yellow: new_colors.yellow.unwrap_or(def_palette.yellow),
        cyan: new_colors.cyan.unwrap_or(def_palette.cyan),
        red: new_colors.red.unwrap_or(def_palette.red),
        grey: new_colors.grey.unwrap_or(def_palette.grey),
        light_grey: new_colors.light_grey.unwrap_or(def_palette.light_grey),
        dark_cyan: new_colors.dark_cyan.unwrap_or(def_palette.dark_cyan),
        dark_red: new_colors.dark_red.unwrap_or(def_palette.dark_red),
        dark_yellow: new_colors.dark_yellow.unwrap_or(def_palette.dark_yellow),
        dark_purple: new_colors.dark_purple.unwrap_or(def_palette.dark_purple),
        diff_add: new_colors.diff_add.unwrap_or(def_palette.diff_add),
        diff_delete: new_colors.diff_delete.unwrap_or(def_palette.diff_delete),
        diff_change: new_colors.diff_change.unwrap_or(def_palette.diff_change),
        diff_text: new_colors.diff_text.unwrap_or(def_palette.diff_text),
    }
}

impl Default for ColorPalette {
    fn default() -> Self {
        let pal;
        {
            match GLOBAL_CONFIG.read() {
                Ok(conf) => pal = get_palette(conf.style),
                Err(_) => pal = get_palette(OneDarkStyle::default()),
            }
        }
        pal
    }
}
