use crate::get_global_config;
use crate::OneDarkStyle;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Debug, Clone)]
#[serde(default)]
pub struct ColorPalette {
    pub black: String,
    pub bg0: String,
    pub bg1: String,
    pub bg2: String,
    pub bg3: String,
    pub bg_d: String,
    pub bg_blue: String,
    pub bg_yellow: String,
    pub fg: String,
    pub purple: String,
    pub green: String,
    pub orange: String,
    pub blue: String,
    pub yellow: String,
    pub cyan: String,
    pub red: String,
    pub grey: String,
    pub light_grey: String,
    pub dark_cyan: String,
    pub dark_red: String,
    pub dark_yellow: String,
    pub dark_purple: String,
    pub diff_add: String,
    pub diff_delete: String,
    pub diff_change: String,
    pub diff_text: String,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ConfigColorPalette {
    pub black: Option<String>,
    pub bg0: Option<String>,
    pub bg1: Option<String>,
    pub bg2: Option<String>,
    pub bg3: Option<String>,
    pub bg_d: Option<String>,
    pub bg_blue: Option<String>,
    pub bg_yellow: Option<String>,
    pub fg: Option<String>,
    pub purple: Option<String>,
    pub green: Option<String>,
    pub orange: Option<String>,
    pub blue: Option<String>,
    pub yellow: Option<String>,
    pub cyan: Option<String>,
    pub red: Option<String>,
    pub grey: Option<String>,
    pub light_grey: Option<String>,
    pub dark_cyan: Option<String>,
    pub dark_red: Option<String>,
    pub dark_yellow: Option<String>,
    pub dark_purple: Option<String>,
    pub diff_add: Option<String>,
    pub diff_delete: Option<String>,
    pub diff_change: Option<String>,
    pub diff_text: Option<String>,
}

pub fn get_palette(style: OneDarkStyle) -> ColorPalette {
    match style {
        OneDarkStyle::Dark => ColorPalette {
            black: "#181a1f".to_string(),
            bg0: "#282c34".to_string(),
            bg1: "#31353f".to_string(),
            bg2: "#393f4a".to_string(),
            bg3: "#3b3f4c".to_string(),
            bg_d: "#21252b".to_string(),
            bg_blue: "#73b8f1".to_string(),
            bg_yellow: "#ebd09c".to_string(),
            fg: "#abb2bf".to_string(),
            purple: "#c678dd".to_string(),
            green: "#98c379".to_string(),
            orange: "#d19a66".to_string(),
            blue: "#61afef".to_string(),
            yellow: "#e5c07b".to_string(),
            cyan: "#56b6c2".to_string(),
            red: "#e86671".to_string(),
            grey: "#5c6370".to_string(),
            light_grey: "#848b98".to_string(),
            dark_cyan: "#2b6f77".to_string(),
            dark_red: "#993939".to_string(),
            dark_yellow: "#93691d".to_string(),
            dark_purple: "#8a3fa0".to_string(),
            diff_add: "#31392b".to_string(),
            diff_delete: "#382b2c".to_string(),
            diff_change: "#1c3448".to_string(),
            diff_text: "#2c5372".to_string(),
        },
        OneDarkStyle::Darker => ColorPalette {
            black: "#0e1013".to_string(),
            bg0: "#1f2329".to_string(),
            bg1: "#282c34".to_string(),
            bg2: "#30363f".to_string(),
            bg3: "#323641".to_string(),
            bg_d: "#181b20".to_string(),
            bg_blue: "#61afef".to_string(),
            bg_yellow: "#e8c88c".to_string(),
            fg: "#a0a8b7".to_string(),
            purple: "#bf68d9".to_string(),
            green: "#8ebd6b".to_string(),
            orange: "#cc9057".to_string(),
            blue: "#4fa6ed".to_string(),
            yellow: "#e2b86b".to_string(),
            cyan: "#48b0bd".to_string(),
            red: "#e55561".to_string(),
            grey: "#535965".to_string(),
            light_grey: "#7a818e".to_string(),
            dark_cyan: "#266269".to_string(),
            dark_red: "#8b3434".to_string(),
            dark_yellow: "#835d1a".to_string(),
            dark_purple: "#7e3992".to_string(),
            diff_add: "#272e23".to_string(),
            diff_delete: "#2d2223".to_string(),
            diff_change: "#172a3a".to_string(),
            diff_text: "#274964".to_string(),
        },
        OneDarkStyle::Cool => ColorPalette {
            black: "#151820".to_string(),
            bg0: "#242b38".to_string(),
            bg1: "#2d3343".to_string(),
            bg2: "#343e4f".to_string(),
            bg3: "#363c51".to_string(),
            bg_d: "#1e242e".to_string(),
            bg_blue: "#6db9f7".to_string(),
            bg_yellow: "#f0d197".to_string(),
            fg: "#a5b0c5".to_string(),
            purple: "#ca72e4".to_string(),
            green: "#97ca72".to_string(),
            orange: "#d99a5e".to_string(),
            blue: "#5ab0f6".to_string(),
            yellow: "#ebc275".to_string(),
            cyan: "#4dbdcb".to_string(),
            red: "#ef5f6b".to_string(),
            grey: "#546178".to_string(),
            light_grey: "#7d899f".to_string(),
            dark_cyan: "#25747d".to_string(),
            dark_red: "#a13131".to_string(),
            dark_yellow: "#9a6b16".to_string(),
            dark_purple: "#8f36a9".to_string(),
            diff_add: "#303d27".to_string(),
            diff_delete: "#3c2729".to_string(),
            diff_change: "#18344c".to_string(),
            diff_text: "#265478".to_string(),
        },
        OneDarkStyle::Deep => ColorPalette {
            black: "#0c0e15".to_string(),
            bg0: "#1a212e".to_string(),
            bg1: "#21283b".to_string(),
            bg2: "#283347".to_string(),
            bg3: "#2a324a".to_string(),
            bg_d: "#141b24".to_string(),
            bg_blue: "#54b0fd".to_string(),
            bg_yellow: "#f2cc81".to_string(),
            fg: "#93a4c3".to_string(),
            purple: "#c75ae8".to_string(),
            green: "#8bcd5b".to_string(),
            orange: "#dd9046".to_string(),
            blue: "#41a7fc".to_string(),
            yellow: "#efbd5d".to_string(),
            cyan: "#34bfd0".to_string(),
            red: "#f65866".to_string(),
            grey: "#455574".to_string(),
            light_grey: "#6c7d9c".to_string(),
            dark_cyan: "#1b6a73".to_string(),
            dark_red: "#992525".to_string(),
            dark_yellow: "#8f610d".to_string(),
            dark_purple: "#862aa1".to_string(),
            diff_add: "#27341c".to_string(),
            diff_delete: "#331c1e".to_string(),
            diff_change: "#102b40".to_string(),
            diff_text: "#1c4a6e".to_string(),
        },
        OneDarkStyle::Warm => ColorPalette {
            black: "#191a1c".to_string(),
            bg0: "#2c2d30".to_string(),
            bg1: "#35373b".to_string(),
            bg2: "#3e4045".to_string(),
            bg3: "#404247".to_string(),
            bg_d: "#242628".to_string(),
            bg_blue: "#79b7eb".to_string(),
            bg_yellow: "#e6cfa1".to_string(),
            fg: "#b1b4b9".to_string(),
            purple: "#c27fd7".to_string(),
            green: "#99bc80".to_string(),
            orange: "#c99a6e".to_string(),
            blue: "#68aee8".to_string(),
            yellow: "#dfbe81".to_string(),
            cyan: "#5fafb9".to_string(),
            red: "#e16d77".to_string(),
            grey: "#646568".to_string(),
            light_grey: "#8b8d91".to_string(),
            dark_cyan: "#316a71".to_string(),
            dark_red: "#914141".to_string(),
            dark_yellow: "#8c6724".to_string(),
            dark_purple: "#854897".to_string(),
            diff_add: "#32352f".to_string(),
            diff_delete: "#342f2f".to_string(),
            diff_change: "#203444".to_string(),
            diff_text: "#32526c".to_string(),
        },
        OneDarkStyle::Warmer => ColorPalette {
            black: "#101012".to_string(),
            bg0: "#232326".to_string(),
            bg1: "#2c2d31".to_string(),
            bg2: "#35363b".to_string(),
            bg3: "#37383d".to_string(),
            bg_d: "#1b1c1e".to_string(),
            bg_blue: "#68aee8".to_string(),
            bg_yellow: "#e2c792".to_string(),
            fg: "#a7aab0".to_string(),
            purple: "#bb70d2".to_string(),
            green: "#8fb573".to_string(),
            orange: "#c49060".to_string(),
            blue: "#57a5e5".to_string(),
            yellow: "#dbb671".to_string(),
            cyan: "#51a8b3".to_string(),
            red: "#de5d68".to_string(),
            grey: "#5a5b5e".to_string(),
            light_grey: "#818387".to_string(),
            dark_cyan: "#2b5d63".to_string(),
            dark_red: "#833b3b".to_string(),
            dark_yellow: "#7c5c20".to_string(),
            dark_purple: "#79428a".to_string(),
            diff_add: "#282b26".to_string(),
            diff_delete: "#2a2626".to_string(),
            diff_change: "#1a2a37".to_string(),
            diff_text: "#2c485f".to_string(),
        },
        OneDarkStyle::Light => ColorPalette {
            black: "#101012".to_string(),
            bg0: "#fafafa".to_string(),
            bg1: "#f0f0f0".to_string(),
            bg2: "#e6e6e6".to_string(),
            bg3: "#dcdcdc".to_string(),
            bg_d: "#c9c9c9".to_string(),
            bg_blue: "#68aee8".to_string(),
            bg_yellow: "#e2c792".to_string(),
            fg: "#383a42".to_string(),
            purple: "#a626a4".to_string(),
            green: "#50a14f".to_string(),
            orange: "#c18401".to_string(),
            blue: "#4078f2".to_string(),
            yellow: "#986801".to_string(),
            cyan: "#0184bc".to_string(),
            red: "#e45649".to_string(),
            grey: "#a0a1a7".to_string(),
            light_grey: "#818387".to_string(),
            dark_cyan: "#2b5d63".to_string(),
            dark_red: "#833b3b".to_string(),
            dark_yellow: "#7c5c20".to_string(),
            dark_purple: "#79428a".to_string(),
            diff_add: "#e2fbe4".to_string(),
            diff_delete: "#fce2e5".to_string(),
            diff_change: "#e2ecfb".to_string(),
            diff_text: "#cad3e0".to_string(),
        },
    }
}

impl Default for ColorPalette {
    fn default() -> Self {
        if let Ok(config) = get_global_config::<ConfigColorPalette>() {
            let style = config.style;
            get_palette(style)
        } else {
            get_palette(OneDarkStyle::default())
        }
    }
}
